"""
Stores all information about the data possibly for later use in the project.
"""
from numpy import array

class info_container():
    custom_stopwords = []

    beer_styles = array([
        "Hefeweizen",
        "English Strong Ale",
        "Foreign / Export Stout",
        "German Pilsener",
        "American Double / Imperial IPA",
        "Herbed / Spiced Beer",
        "Oatmeal Stout",
        "American Pale Lager",
        "Rauchbier",
        "American Pale Ale (APA)",
        "American Porter",
        "Belgian Strong Dark Ale",
        "American Stout",
        "Russian Imperial Stout",
        "American Amber / Red Ale",
        "American Strong Ale",
        "American Adjunct Lager",
        "American Blonde Ale",
        "American IPA",
        "Fruit / Vegetable Beer",
        "American Double / Imperial Stout",
        "English Bitter",
        "English Porter",
        "Irish Dry Stout",
        "American Barleywine",
        "Belgian Strong Pale Ale",
        "Doppelbock",
        "Maibock / Helles Bock",
        "Light Lager",
        "Pumpkin Ale",
        "Dortmunder / Export Lager",
        "Euro Strong Lager",
        "Euro Dark Lager",
        "Low Alcohol Beer",
        "Euro Pale Lager",
        "Bock",
        "English India Pale Ale (IPA)",
        "Altbier",
        "Munich Dunkel Lager",
        "Rye Beer",
        "American Pale Wheat Ale",
        "Milk / Sweet Stout",
        "Schwarzbier",
        "Vienna Lager",
        "American Amber / Red Lager",
        "Scottish Ale",
        "Witbier",
        "Saison / Farmhouse Ale",
        "English Brown Ale",
        "American Black Ale",
        "English Barleywine",
        "English Dark Mild Ale",
        "Extra Special / Strong Bitter (ESB)",
        "California Common / Steam Beer",
        "Scotch Ale / Wee Heavy",
        "English Pale Ale",
        "Belgian IPA",
        "Belgian Pale Ale",
        "Tripel",
        "Flanders Oud Bruin",
        "Czech Pilsener",
        "American Brown Ale",
        "Smoked Beer",
        "Flanders Red Ale",
        "Dunkelweizen",
        "Dubbel",
        "Roggenbier",
        "Keller Bier / Zwickel Bier",
        "Belgian Dark Ale",
        "Winter Warmer",
        "Japanese Rice Lager",
        "Black & Tan",
        "Irish Red Ale",
        "Chile Beer",
        "English Stout",
        "Cream Ale",
        "American Wild Ale",
        "Weizenbock",
        "American Double / Imperial Pilsner",
        "Scottish Gruit / Ancient Herbed Ale",
        "Wheatwine",
        "American Dark Wheat Ale",
        "American Malt Liquor",
        "Baltic Porter",
        "Munich Helles Lager",
        "Kristalweizen",
        "English Pale Mild Ale",
        "Lambic - Fruit",
        "Old Ale",
        "Quadrupel (Quad)",
        "Braggot",
        "Lambic - Unblended",
        "Eisbock",
        "Berliner Weissbier",
        "Kvass",
        "Faro",
        "Gueuze",
        "Gose",
        "Happoshu",
        "Sahti",]).tolist()
